//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class App_SpartansCustom_Entities : DbContext
    {
        public App_SpartansCustom_Entities()
            : base("name=App_SpartansCustom_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbCiudades> tbCiudades { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEmpresa> tbEmpresa { get; set; }
        public virtual DbSet<tbPais> tbPais { get; set; }
        public virtual DbSet<tbClientes> tbClientes { get; set; }
        public virtual DbSet<tbRangos> tbRangos { get; set; }
        public virtual DbSet<tbCatalogoProductos> tbCatalogoProductos { get; set; }
        public virtual DbSet<tbCategoriaProductos> tbCategoriaProductos { get; set; }
        public virtual DbSet<tbImagenProductos> tbImagenProductos { get; set; }
        public virtual DbSet<tbMarcasComerciales> tbMarcasComerciales { get; set; }
        public virtual DbSet<tbProductos> tbProductos { get; set; }
        public virtual DbSet<tbSubCategoriaProductos> tbSubCategoriaProductos { get; set; }
        public virtual DbSet<tbPantallas> tbPantallas { get; set; }
        public virtual DbSet<tbPantallasRoles> tbPantallasRoles { get; set; }
        public virtual DbSet<tbPermisos> tbPermisos { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbRolesPermisos> tbRolesPermisos { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbUsuariosRoles> tbUsuariosRoles { get; set; }
        public virtual DbSet<tbPersonas> tbPersonas { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbCiudades_Delete(Nullable<int> ciud_Id, Nullable<int> ciud_UsuarioModifica)
        {
            var ciud_IdParameter = ciud_Id.HasValue ?
                new ObjectParameter("ciud_Id", ciud_Id) :
                new ObjectParameter("ciud_Id", typeof(int));
    
            var ciud_UsuarioModificaParameter = ciud_UsuarioModifica.HasValue ?
                new ObjectParameter("ciud_UsuarioModifica", ciud_UsuarioModifica) :
                new ObjectParameter("ciud_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbCiudades_Delete", ciud_IdParameter, ciud_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbCiudades_Insert(string ciud_Descripcion, Nullable<int> ciud_CodigoPostal, Nullable<int> depto_Id, Nullable<bool> ciud_EsActivo, Nullable<int> ciud_UsuarioCrea)
        {
            var ciud_DescripcionParameter = ciud_Descripcion != null ?
                new ObjectParameter("ciud_Descripcion", ciud_Descripcion) :
                new ObjectParameter("ciud_Descripcion", typeof(string));
    
            var ciud_CodigoPostalParameter = ciud_CodigoPostal.HasValue ?
                new ObjectParameter("ciud_CodigoPostal", ciud_CodigoPostal) :
                new ObjectParameter("ciud_CodigoPostal", typeof(int));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var ciud_EsActivoParameter = ciud_EsActivo.HasValue ?
                new ObjectParameter("ciud_EsActivo", ciud_EsActivo) :
                new ObjectParameter("ciud_EsActivo", typeof(bool));
    
            var ciud_UsuarioCreaParameter = ciud_UsuarioCrea.HasValue ?
                new ObjectParameter("ciud_UsuarioCrea", ciud_UsuarioCrea) :
                new ObjectParameter("ciud_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbCiudades_Insert", ciud_DescripcionParameter, ciud_CodigoPostalParameter, depto_IdParameter, ciud_EsActivoParameter, ciud_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbCiudades_Update(Nullable<int> ciud_Id, string ciud_Descripcion, Nullable<int> ciud_CodigoPostal, Nullable<int> depto_Id, Nullable<bool> ciud_EsActivo, Nullable<int> ciud_UsuarioModifica)
        {
            var ciud_IdParameter = ciud_Id.HasValue ?
                new ObjectParameter("ciud_Id", ciud_Id) :
                new ObjectParameter("ciud_Id", typeof(int));
    
            var ciud_DescripcionParameter = ciud_Descripcion != null ?
                new ObjectParameter("ciud_Descripcion", ciud_Descripcion) :
                new ObjectParameter("ciud_Descripcion", typeof(string));
    
            var ciud_CodigoPostalParameter = ciud_CodigoPostal.HasValue ?
                new ObjectParameter("ciud_CodigoPostal", ciud_CodigoPostal) :
                new ObjectParameter("ciud_CodigoPostal", typeof(int));
    
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var ciud_EsActivoParameter = ciud_EsActivo.HasValue ?
                new ObjectParameter("ciud_EsActivo", ciud_EsActivo) :
                new ObjectParameter("ciud_EsActivo", typeof(bool));
    
            var ciud_UsuarioModificaParameter = ciud_UsuarioModifica.HasValue ?
                new ObjectParameter("ciud_UsuarioModifica", ciud_UsuarioModifica) :
                new ObjectParameter("ciud_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbCiudades_Update", ciud_IdParameter, ciud_DescripcionParameter, ciud_CodigoPostalParameter, depto_IdParameter, ciud_EsActivoParameter, ciud_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbEmpresa_Insert(string empr_NombreEmpresa, string empr_ImagenLogo, string empr_ImagenPortada, string empr_NombreUsuarioFacebook, string empr_NombreUsuarioInstagram, string empr_NombreUsuarioTwitter, string empr_Telefono, string empr_CorreoElectronico, Nullable<int> empr_UsuarioCrea)
        {
            var empr_NombreEmpresaParameter = empr_NombreEmpresa != null ?
                new ObjectParameter("empr_NombreEmpresa", empr_NombreEmpresa) :
                new ObjectParameter("empr_NombreEmpresa", typeof(string));
    
            var empr_ImagenLogoParameter = empr_ImagenLogo != null ?
                new ObjectParameter("empr_ImagenLogo", empr_ImagenLogo) :
                new ObjectParameter("empr_ImagenLogo", typeof(string));
    
            var empr_ImagenPortadaParameter = empr_ImagenPortada != null ?
                new ObjectParameter("empr_ImagenPortada", empr_ImagenPortada) :
                new ObjectParameter("empr_ImagenPortada", typeof(string));
    
            var empr_NombreUsuarioFacebookParameter = empr_NombreUsuarioFacebook != null ?
                new ObjectParameter("empr_NombreUsuarioFacebook", empr_NombreUsuarioFacebook) :
                new ObjectParameter("empr_NombreUsuarioFacebook", typeof(string));
    
            var empr_NombreUsuarioInstagramParameter = empr_NombreUsuarioInstagram != null ?
                new ObjectParameter("empr_NombreUsuarioInstagram", empr_NombreUsuarioInstagram) :
                new ObjectParameter("empr_NombreUsuarioInstagram", typeof(string));
    
            var empr_NombreUsuarioTwitterParameter = empr_NombreUsuarioTwitter != null ?
                new ObjectParameter("empr_NombreUsuarioTwitter", empr_NombreUsuarioTwitter) :
                new ObjectParameter("empr_NombreUsuarioTwitter", typeof(string));
    
            var empr_TelefonoParameter = empr_Telefono != null ?
                new ObjectParameter("empr_Telefono", empr_Telefono) :
                new ObjectParameter("empr_Telefono", typeof(string));
    
            var empr_CorreoElectronicoParameter = empr_CorreoElectronico != null ?
                new ObjectParameter("empr_CorreoElectronico", empr_CorreoElectronico) :
                new ObjectParameter("empr_CorreoElectronico", typeof(string));
    
            var empr_UsuarioCreaParameter = empr_UsuarioCrea.HasValue ?
                new ObjectParameter("empr_UsuarioCrea", empr_UsuarioCrea) :
                new ObjectParameter("empr_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbEmpresa_Insert", empr_NombreEmpresaParameter, empr_ImagenLogoParameter, empr_ImagenPortadaParameter, empr_NombreUsuarioFacebookParameter, empr_NombreUsuarioInstagramParameter, empr_NombreUsuarioTwitterParameter, empr_TelefonoParameter, empr_CorreoElectronicoParameter, empr_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbEmpresa_Update(Nullable<int> empr_Id, string empr_NombreEmpresa, string empr_ImagenLogo, string empr_ImagenPortada, string empr_NombreUsuarioFacebook, string empr_NombreUsuarioInstagram, string empr_NombreUsuarioTwitter, string empr_Telefono, string empr_CorreoElectronico, Nullable<int> empr_UsuarioModifica)
        {
            var empr_IdParameter = empr_Id.HasValue ?
                new ObjectParameter("empr_Id", empr_Id) :
                new ObjectParameter("empr_Id", typeof(int));
    
            var empr_NombreEmpresaParameter = empr_NombreEmpresa != null ?
                new ObjectParameter("empr_NombreEmpresa", empr_NombreEmpresa) :
                new ObjectParameter("empr_NombreEmpresa", typeof(string));
    
            var empr_ImagenLogoParameter = empr_ImagenLogo != null ?
                new ObjectParameter("empr_ImagenLogo", empr_ImagenLogo) :
                new ObjectParameter("empr_ImagenLogo", typeof(string));
    
            var empr_ImagenPortadaParameter = empr_ImagenPortada != null ?
                new ObjectParameter("empr_ImagenPortada", empr_ImagenPortada) :
                new ObjectParameter("empr_ImagenPortada", typeof(string));
    
            var empr_NombreUsuarioFacebookParameter = empr_NombreUsuarioFacebook != null ?
                new ObjectParameter("empr_NombreUsuarioFacebook", empr_NombreUsuarioFacebook) :
                new ObjectParameter("empr_NombreUsuarioFacebook", typeof(string));
    
            var empr_NombreUsuarioInstagramParameter = empr_NombreUsuarioInstagram != null ?
                new ObjectParameter("empr_NombreUsuarioInstagram", empr_NombreUsuarioInstagram) :
                new ObjectParameter("empr_NombreUsuarioInstagram", typeof(string));
    
            var empr_NombreUsuarioTwitterParameter = empr_NombreUsuarioTwitter != null ?
                new ObjectParameter("empr_NombreUsuarioTwitter", empr_NombreUsuarioTwitter) :
                new ObjectParameter("empr_NombreUsuarioTwitter", typeof(string));
    
            var empr_TelefonoParameter = empr_Telefono != null ?
                new ObjectParameter("empr_Telefono", empr_Telefono) :
                new ObjectParameter("empr_Telefono", typeof(string));
    
            var empr_CorreoElectronicoParameter = empr_CorreoElectronico != null ?
                new ObjectParameter("empr_CorreoElectronico", empr_CorreoElectronico) :
                new ObjectParameter("empr_CorreoElectronico", typeof(string));
    
            var empr_UsuarioModificaParameter = empr_UsuarioModifica.HasValue ?
                new ObjectParameter("empr_UsuarioModifica", empr_UsuarioModifica) :
                new ObjectParameter("empr_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbEmpresa_Update", empr_IdParameter, empr_NombreEmpresaParameter, empr_ImagenLogoParameter, empr_ImagenPortadaParameter, empr_NombreUsuarioFacebookParameter, empr_NombreUsuarioInstagramParameter, empr_NombreUsuarioTwitterParameter, empr_TelefonoParameter, empr_CorreoElectronicoParameter, empr_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbPais_Delete(Nullable<int> pais_Id, Nullable<int> pais_UsuarioModifica)
        {
            var pais_IdParameter = pais_Id.HasValue ?
                new ObjectParameter("pais_Id", pais_Id) :
                new ObjectParameter("pais_Id", typeof(int));
    
            var pais_UsuarioModificaParameter = pais_UsuarioModifica.HasValue ?
                new ObjectParameter("pais_UsuarioModifica", pais_UsuarioModifica) :
                new ObjectParameter("pais_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbPais_Delete", pais_IdParameter, pais_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbPais_Insert(string pais_Descripcion, Nullable<int> pais_CodigoPais, Nullable<bool> pais_EsActivo, Nullable<int> pais_UsuarioCrea)
        {
            var pais_DescripcionParameter = pais_Descripcion != null ?
                new ObjectParameter("pais_Descripcion", pais_Descripcion) :
                new ObjectParameter("pais_Descripcion", typeof(string));
    
            var pais_CodigoPaisParameter = pais_CodigoPais.HasValue ?
                new ObjectParameter("pais_CodigoPais", pais_CodigoPais) :
                new ObjectParameter("pais_CodigoPais", typeof(int));
    
            var pais_EsActivoParameter = pais_EsActivo.HasValue ?
                new ObjectParameter("pais_EsActivo", pais_EsActivo) :
                new ObjectParameter("pais_EsActivo", typeof(bool));
    
            var pais_UsuarioCreaParameter = pais_UsuarioCrea.HasValue ?
                new ObjectParameter("pais_UsuarioCrea", pais_UsuarioCrea) :
                new ObjectParameter("pais_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbPais_Insert", pais_DescripcionParameter, pais_CodigoPaisParameter, pais_EsActivoParameter, pais_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Gral_tbPais_Update(Nullable<int> pais_Id, string pais_Descripcion, Nullable<int> pais_CodigoPais, Nullable<int> pais_UsuarioModifica)
        {
            var pais_IdParameter = pais_Id.HasValue ?
                new ObjectParameter("pais_Id", pais_Id) :
                new ObjectParameter("pais_Id", typeof(int));
    
            var pais_DescripcionParameter = pais_Descripcion != null ?
                new ObjectParameter("pais_Descripcion", pais_Descripcion) :
                new ObjectParameter("pais_Descripcion", typeof(string));
    
            var pais_CodigoPaisParameter = pais_CodigoPais.HasValue ?
                new ObjectParameter("pais_CodigoPais", pais_CodigoPais) :
                new ObjectParameter("pais_CodigoPais", typeof(int));
    
            var pais_UsuarioModificaParameter = pais_UsuarioModifica.HasValue ?
                new ObjectParameter("pais_UsuarioModifica", pais_UsuarioModifica) :
                new ObjectParameter("pais_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Gral_tbPais_Update", pais_IdParameter, pais_DescripcionParameter, pais_CodigoPaisParameter, pais_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UPD_Gral_tbDepartamentos_Delete(Nullable<int> depto_Id, Nullable<int> depto_UsuarioModifica)
        {
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var depto_UsuarioModificaParameter = depto_UsuarioModifica.HasValue ?
                new ObjectParameter("depto_UsuarioModifica", depto_UsuarioModifica) :
                new ObjectParameter("depto_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UPD_Gral_tbDepartamentos_Delete", depto_IdParameter, depto_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UPD_Gral_tbDepartamentos_Insert(string depto_Descripcion, Nullable<int> depto_CodigoDepartamento, Nullable<int> pais_Id, Nullable<bool> depto_EsActivo, Nullable<int> depto_UsuarioCrea)
        {
            var depto_DescripcionParameter = depto_Descripcion != null ?
                new ObjectParameter("depto_Descripcion", depto_Descripcion) :
                new ObjectParameter("depto_Descripcion", typeof(string));
    
            var depto_CodigoDepartamentoParameter = depto_CodigoDepartamento.HasValue ?
                new ObjectParameter("depto_CodigoDepartamento", depto_CodigoDepartamento) :
                new ObjectParameter("depto_CodigoDepartamento", typeof(int));
    
            var pais_IdParameter = pais_Id.HasValue ?
                new ObjectParameter("pais_Id", pais_Id) :
                new ObjectParameter("pais_Id", typeof(int));
    
            var depto_EsActivoParameter = depto_EsActivo.HasValue ?
                new ObjectParameter("depto_EsActivo", depto_EsActivo) :
                new ObjectParameter("depto_EsActivo", typeof(bool));
    
            var depto_UsuarioCreaParameter = depto_UsuarioCrea.HasValue ?
                new ObjectParameter("depto_UsuarioCrea", depto_UsuarioCrea) :
                new ObjectParameter("depto_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UPD_Gral_tbDepartamentos_Insert", depto_DescripcionParameter, depto_CodigoDepartamentoParameter, pais_IdParameter, depto_EsActivoParameter, depto_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UPD_Gral_tbDepartamentos_Update(Nullable<int> depto_Id, string depto_Descripcion, Nullable<int> depto_CodigoDepartamento, Nullable<int> pais_Id, Nullable<int> depto_UsuarioModifica)
        {
            var depto_IdParameter = depto_Id.HasValue ?
                new ObjectParameter("depto_Id", depto_Id) :
                new ObjectParameter("depto_Id", typeof(int));
    
            var depto_DescripcionParameter = depto_Descripcion != null ?
                new ObjectParameter("depto_Descripcion", depto_Descripcion) :
                new ObjectParameter("depto_Descripcion", typeof(string));
    
            var depto_CodigoDepartamentoParameter = depto_CodigoDepartamento.HasValue ?
                new ObjectParameter("depto_CodigoDepartamento", depto_CodigoDepartamento) :
                new ObjectParameter("depto_CodigoDepartamento", typeof(int));
    
            var pais_IdParameter = pais_Id.HasValue ?
                new ObjectParameter("pais_Id", pais_Id) :
                new ObjectParameter("pais_Id", typeof(int));
    
            var depto_UsuarioModificaParameter = depto_UsuarioModifica.HasValue ?
                new ObjectParameter("depto_UsuarioModifica", depto_UsuarioModifica) :
                new ObjectParameter("depto_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UPD_Gral_tbDepartamentos_Update", depto_IdParameter, depto_DescripcionParameter, depto_CodigoDepartamentoParameter, pais_IdParameter, depto_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbClientes_Delete(Nullable<int> clte_Id, Nullable<int> clte_UsuarioModifica)
        {
            var clte_IdParameter = clte_Id.HasValue ?
                new ObjectParameter("clte_Id", clte_Id) :
                new ObjectParameter("clte_Id", typeof(int));
    
            var clte_UsuarioModificaParameter = clte_UsuarioModifica.HasValue ?
                new ObjectParameter("clte_UsuarioModifica", clte_UsuarioModifica) :
                new ObjectParameter("clte_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbClientes_Delete", clte_IdParameter, clte_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbClientes_Insert(Nullable<int> clte_Cargo, Nullable<int> rang_Id, Nullable<bool> clte_EsActivo, Nullable<int> per_Id, Nullable<bool> clte_Estado, Nullable<int> clte_UsuarioCrea)
        {
            var clte_CargoParameter = clte_Cargo.HasValue ?
                new ObjectParameter("clte_Cargo", clte_Cargo) :
                new ObjectParameter("clte_Cargo", typeof(int));
    
            var rang_IdParameter = rang_Id.HasValue ?
                new ObjectParameter("rang_Id", rang_Id) :
                new ObjectParameter("rang_Id", typeof(int));
    
            var clte_EsActivoParameter = clte_EsActivo.HasValue ?
                new ObjectParameter("clte_EsActivo", clte_EsActivo) :
                new ObjectParameter("clte_EsActivo", typeof(bool));
    
            var per_IdParameter = per_Id.HasValue ?
                new ObjectParameter("per_Id", per_Id) :
                new ObjectParameter("per_Id", typeof(int));
    
            var clte_EstadoParameter = clte_Estado.HasValue ?
                new ObjectParameter("clte_Estado", clte_Estado) :
                new ObjectParameter("clte_Estado", typeof(bool));
    
            var clte_UsuarioCreaParameter = clte_UsuarioCrea.HasValue ?
                new ObjectParameter("clte_UsuarioCrea", clte_UsuarioCrea) :
                new ObjectParameter("clte_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbClientes_Insert", clte_CargoParameter, rang_IdParameter, clte_EsActivoParameter, per_IdParameter, clte_EstadoParameter, clte_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbClientes_Update(Nullable<int> clte_Id, Nullable<int> clte_Cargo, Nullable<int> rang_Id, Nullable<int> per_Id, Nullable<int> clte_EsActivo, Nullable<int> clte_UsuarioModifica)
        {
            var clte_IdParameter = clte_Id.HasValue ?
                new ObjectParameter("clte_Id", clte_Id) :
                new ObjectParameter("clte_Id", typeof(int));
    
            var clte_CargoParameter = clte_Cargo.HasValue ?
                new ObjectParameter("clte_Cargo", clte_Cargo) :
                new ObjectParameter("clte_Cargo", typeof(int));
    
            var rang_IdParameter = rang_Id.HasValue ?
                new ObjectParameter("rang_Id", rang_Id) :
                new ObjectParameter("rang_Id", typeof(int));
    
            var per_IdParameter = per_Id.HasValue ?
                new ObjectParameter("per_Id", per_Id) :
                new ObjectParameter("per_Id", typeof(int));
    
            var clte_EsActivoParameter = clte_EsActivo.HasValue ?
                new ObjectParameter("clte_EsActivo", clte_EsActivo) :
                new ObjectParameter("clte_EsActivo", typeof(int));
    
            var clte_UsuarioModificaParameter = clte_UsuarioModifica.HasValue ?
                new ObjectParameter("clte_UsuarioModifica", clte_UsuarioModifica) :
                new ObjectParameter("clte_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbClientes_Update", clte_IdParameter, clte_CargoParameter, rang_IdParameter, per_IdParameter, clte_EsActivoParameter, clte_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbDirecciones_Delete(Nullable<int> dir_Id, Nullable<int> dir_UsuarioModifica)
        {
            var dir_IdParameter = dir_Id.HasValue ?
                new ObjectParameter("dir_Id", dir_Id) :
                new ObjectParameter("dir_Id", typeof(int));
    
            var dir_UsuarioModificaParameter = dir_UsuarioModifica.HasValue ?
                new ObjectParameter("dir_UsuarioModifica", dir_UsuarioModifica) :
                new ObjectParameter("dir_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbDirecciones_Delete", dir_IdParameter, dir_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbDirecciones_Insert(string dir_Descripcion1, string dir_Descripcion2, Nullable<int> ciud_Id, string dir_TipoEntidad, Nullable<System.DateTime> dir_FechaFinUsoDireccion, Nullable<int> dir_UsuarioCrea)
        {
            var dir_Descripcion1Parameter = dir_Descripcion1 != null ?
                new ObjectParameter("dir_Descripcion1", dir_Descripcion1) :
                new ObjectParameter("dir_Descripcion1", typeof(string));
    
            var dir_Descripcion2Parameter = dir_Descripcion2 != null ?
                new ObjectParameter("dir_Descripcion2", dir_Descripcion2) :
                new ObjectParameter("dir_Descripcion2", typeof(string));
    
            var ciud_IdParameter = ciud_Id.HasValue ?
                new ObjectParameter("ciud_Id", ciud_Id) :
                new ObjectParameter("ciud_Id", typeof(int));
    
            var dir_TipoEntidadParameter = dir_TipoEntidad != null ?
                new ObjectParameter("dir_TipoEntidad", dir_TipoEntidad) :
                new ObjectParameter("dir_TipoEntidad", typeof(string));
    
            var dir_FechaFinUsoDireccionParameter = dir_FechaFinUsoDireccion.HasValue ?
                new ObjectParameter("dir_FechaFinUsoDireccion", dir_FechaFinUsoDireccion) :
                new ObjectParameter("dir_FechaFinUsoDireccion", typeof(System.DateTime));
    
            var dir_UsuarioCreaParameter = dir_UsuarioCrea.HasValue ?
                new ObjectParameter("dir_UsuarioCrea", dir_UsuarioCrea) :
                new ObjectParameter("dir_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbDirecciones_Insert", dir_Descripcion1Parameter, dir_Descripcion2Parameter, ciud_IdParameter, dir_TipoEntidadParameter, dir_FechaFinUsoDireccionParameter, dir_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbDirecciones_Update(Nullable<int> dir_Id, string dir_Descripcion1, string dir_Descripcion2, Nullable<int> ciud_Id, string dir_TipoEntidad, Nullable<System.DateTime> dir_FechaFinUsoDireccion, Nullable<int> dir_UsuarioModifica)
        {
            var dir_IdParameter = dir_Id.HasValue ?
                new ObjectParameter("dir_Id", dir_Id) :
                new ObjectParameter("dir_Id", typeof(int));
    
            var dir_Descripcion1Parameter = dir_Descripcion1 != null ?
                new ObjectParameter("dir_Descripcion1", dir_Descripcion1) :
                new ObjectParameter("dir_Descripcion1", typeof(string));
    
            var dir_Descripcion2Parameter = dir_Descripcion2 != null ?
                new ObjectParameter("dir_Descripcion2", dir_Descripcion2) :
                new ObjectParameter("dir_Descripcion2", typeof(string));
    
            var ciud_IdParameter = ciud_Id.HasValue ?
                new ObjectParameter("ciud_Id", ciud_Id) :
                new ObjectParameter("ciud_Id", typeof(int));
    
            var dir_TipoEntidadParameter = dir_TipoEntidad != null ?
                new ObjectParameter("dir_TipoEntidad", dir_TipoEntidad) :
                new ObjectParameter("dir_TipoEntidad", typeof(string));
    
            var dir_FechaFinUsoDireccionParameter = dir_FechaFinUsoDireccion.HasValue ?
                new ObjectParameter("dir_FechaFinUsoDireccion", dir_FechaFinUsoDireccion) :
                new ObjectParameter("dir_FechaFinUsoDireccion", typeof(System.DateTime));
    
            var dir_UsuarioModificaParameter = dir_UsuarioModifica.HasValue ?
                new ObjectParameter("dir_UsuarioModifica", dir_UsuarioModifica) :
                new ObjectParameter("dir_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbDirecciones_Update", dir_IdParameter, dir_Descripcion1Parameter, dir_Descripcion2Parameter, ciud_IdParameter, dir_TipoEntidadParameter, dir_FechaFinUsoDireccionParameter, dir_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbPersonas_Delete(Nullable<int> per_Id, Nullable<int> per_UsuarioModifica)
        {
            var per_IdParameter = per_Id.HasValue ?
                new ObjectParameter("per_Id", per_Id) :
                new ObjectParameter("per_Id", typeof(int));
    
            var per_UsuarioModificaParameter = per_UsuarioModifica.HasValue ?
                new ObjectParameter("per_UsuarioModifica", per_UsuarioModifica) :
                new ObjectParameter("per_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbPersonas_Delete", per_IdParameter, per_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbPersonas_Insert(string per_NumeroIdentidad, string per_Nombres, string per_Apellidos, Nullable<System.DateTime> per_FechaNacimiento, string per_sexo, string per_Telefono, string per_CorreoElectronico, string per_Fotografia, Nullable<bool> per_EsPersonaNatural, Nullable<int> per_UsuarioCrea)
        {
            var per_NumeroIdentidadParameter = per_NumeroIdentidad != null ?
                new ObjectParameter("per_NumeroIdentidad", per_NumeroIdentidad) :
                new ObjectParameter("per_NumeroIdentidad", typeof(string));
    
            var per_NombresParameter = per_Nombres != null ?
                new ObjectParameter("per_Nombres", per_Nombres) :
                new ObjectParameter("per_Nombres", typeof(string));
    
            var per_ApellidosParameter = per_Apellidos != null ?
                new ObjectParameter("per_Apellidos", per_Apellidos) :
                new ObjectParameter("per_Apellidos", typeof(string));
    
            var per_FechaNacimientoParameter = per_FechaNacimiento.HasValue ?
                new ObjectParameter("per_FechaNacimiento", per_FechaNacimiento) :
                new ObjectParameter("per_FechaNacimiento", typeof(System.DateTime));
    
            var per_sexoParameter = per_sexo != null ?
                new ObjectParameter("per_sexo", per_sexo) :
                new ObjectParameter("per_sexo", typeof(string));
    
            var per_TelefonoParameter = per_Telefono != null ?
                new ObjectParameter("per_Telefono", per_Telefono) :
                new ObjectParameter("per_Telefono", typeof(string));
    
            var per_CorreoElectronicoParameter = per_CorreoElectronico != null ?
                new ObjectParameter("per_CorreoElectronico", per_CorreoElectronico) :
                new ObjectParameter("per_CorreoElectronico", typeof(string));
    
            var per_FotografiaParameter = per_Fotografia != null ?
                new ObjectParameter("per_Fotografia", per_Fotografia) :
                new ObjectParameter("per_Fotografia", typeof(string));
    
            var per_EsPersonaNaturalParameter = per_EsPersonaNatural.HasValue ?
                new ObjectParameter("per_EsPersonaNatural", per_EsPersonaNatural) :
                new ObjectParameter("per_EsPersonaNatural", typeof(bool));
    
            var per_UsuarioCreaParameter = per_UsuarioCrea.HasValue ?
                new ObjectParameter("per_UsuarioCrea", per_UsuarioCrea) :
                new ObjectParameter("per_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbPersonas_Insert", per_NumeroIdentidadParameter, per_NombresParameter, per_ApellidosParameter, per_FechaNacimientoParameter, per_sexoParameter, per_TelefonoParameter, per_CorreoElectronicoParameter, per_FotografiaParameter, per_EsPersonaNaturalParameter, per_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbPersonas_Update(Nullable<int> per_Id, string per_NumeroIdentidad, string per_Nombres, string per_Apellidos, Nullable<System.DateTime> per_FechaNacimiento, string per_sexo, string per_Telefono, string per_CorreoElectronico, string per_Fotografia, Nullable<bool> per_EsPersonaNatural, Nullable<int> per_UsuarioModifica, Nullable<System.DateTime> per_FechaModifica)
        {
            var per_IdParameter = per_Id.HasValue ?
                new ObjectParameter("per_Id", per_Id) :
                new ObjectParameter("per_Id", typeof(int));
    
            var per_NumeroIdentidadParameter = per_NumeroIdentidad != null ?
                new ObjectParameter("per_NumeroIdentidad", per_NumeroIdentidad) :
                new ObjectParameter("per_NumeroIdentidad", typeof(string));
    
            var per_NombresParameter = per_Nombres != null ?
                new ObjectParameter("per_Nombres", per_Nombres) :
                new ObjectParameter("per_Nombres", typeof(string));
    
            var per_ApellidosParameter = per_Apellidos != null ?
                new ObjectParameter("per_Apellidos", per_Apellidos) :
                new ObjectParameter("per_Apellidos", typeof(string));
    
            var per_FechaNacimientoParameter = per_FechaNacimiento.HasValue ?
                new ObjectParameter("per_FechaNacimiento", per_FechaNacimiento) :
                new ObjectParameter("per_FechaNacimiento", typeof(System.DateTime));
    
            var per_sexoParameter = per_sexo != null ?
                new ObjectParameter("per_sexo", per_sexo) :
                new ObjectParameter("per_sexo", typeof(string));
    
            var per_TelefonoParameter = per_Telefono != null ?
                new ObjectParameter("per_Telefono", per_Telefono) :
                new ObjectParameter("per_Telefono", typeof(string));
    
            var per_CorreoElectronicoParameter = per_CorreoElectronico != null ?
                new ObjectParameter("per_CorreoElectronico", per_CorreoElectronico) :
                new ObjectParameter("per_CorreoElectronico", typeof(string));
    
            var per_FotografiaParameter = per_Fotografia != null ?
                new ObjectParameter("per_Fotografia", per_Fotografia) :
                new ObjectParameter("per_Fotografia", typeof(string));
    
            var per_EsPersonaNaturalParameter = per_EsPersonaNatural.HasValue ?
                new ObjectParameter("per_EsPersonaNatural", per_EsPersonaNatural) :
                new ObjectParameter("per_EsPersonaNatural", typeof(bool));
    
            var per_UsuarioModificaParameter = per_UsuarioModifica.HasValue ?
                new ObjectParameter("per_UsuarioModifica", per_UsuarioModifica) :
                new ObjectParameter("per_UsuarioModifica", typeof(int));
    
            var per_FechaModificaParameter = per_FechaModifica.HasValue ?
                new ObjectParameter("per_FechaModifica", per_FechaModifica) :
                new ObjectParameter("per_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbPersonas_Update", per_IdParameter, per_NumeroIdentidadParameter, per_NombresParameter, per_ApellidosParameter, per_FechaNacimientoParameter, per_sexoParameter, per_TelefonoParameter, per_CorreoElectronicoParameter, per_FotografiaParameter, per_EsPersonaNaturalParameter, per_UsuarioModificaParameter, per_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbRangos_Delete(Nullable<int> rang_Id, Nullable<int> rang_UsuarioModifica)
        {
            var rang_IdParameter = rang_Id.HasValue ?
                new ObjectParameter("rang_Id", rang_Id) :
                new ObjectParameter("rang_Id", typeof(int));
    
            var rang_UsuarioModificaParameter = rang_UsuarioModifica.HasValue ?
                new ObjectParameter("rang_UsuarioModifica", rang_UsuarioModifica) :
                new ObjectParameter("rang_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbRangos_Delete", rang_IdParameter, rang_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbRangos_Insert(string rang_Descripcion, Nullable<bool> rang_Estado, Nullable<int> rang_UsuarioCrea, Nullable<System.DateTime> rang_FechaCrea, Nullable<int> rang_UsuarioModifica, Nullable<System.DateTime> rang_FechaModifica)
        {
            var rang_DescripcionParameter = rang_Descripcion != null ?
                new ObjectParameter("rang_Descripcion", rang_Descripcion) :
                new ObjectParameter("rang_Descripcion", typeof(string));
    
            var rang_EstadoParameter = rang_Estado.HasValue ?
                new ObjectParameter("rang_Estado", rang_Estado) :
                new ObjectParameter("rang_Estado", typeof(bool));
    
            var rang_UsuarioCreaParameter = rang_UsuarioCrea.HasValue ?
                new ObjectParameter("rang_UsuarioCrea", rang_UsuarioCrea) :
                new ObjectParameter("rang_UsuarioCrea", typeof(int));
    
            var rang_FechaCreaParameter = rang_FechaCrea.HasValue ?
                new ObjectParameter("rang_FechaCrea", rang_FechaCrea) :
                new ObjectParameter("rang_FechaCrea", typeof(System.DateTime));
    
            var rang_UsuarioModificaParameter = rang_UsuarioModifica.HasValue ?
                new ObjectParameter("rang_UsuarioModifica", rang_UsuarioModifica) :
                new ObjectParameter("rang_UsuarioModifica", typeof(int));
    
            var rang_FechaModificaParameter = rang_FechaModifica.HasValue ?
                new ObjectParameter("rang_FechaModifica", rang_FechaModifica) :
                new ObjectParameter("rang_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbRangos_Insert", rang_DescripcionParameter, rang_EstadoParameter, rang_UsuarioCreaParameter, rang_FechaCreaParameter, rang_UsuarioModificaParameter, rang_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Person_tbRangos_Update(Nullable<int> rang_Id, string rang_Descripcion, Nullable<int> rang_UsuarioModifica)
        {
            var rang_IdParameter = rang_Id.HasValue ?
                new ObjectParameter("rang_Id", rang_Id) :
                new ObjectParameter("rang_Id", typeof(int));
    
            var rang_DescripcionParameter = rang_Descripcion != null ?
                new ObjectParameter("rang_Descripcion", rang_Descripcion) :
                new ObjectParameter("rang_Descripcion", typeof(string));
    
            var rang_UsuarioModificaParameter = rang_UsuarioModifica.HasValue ?
                new ObjectParameter("rang_UsuarioModifica", rang_UsuarioModifica) :
                new ObjectParameter("rang_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Person_tbRangos_Update", rang_IdParameter, rang_DescripcionParameter, rang_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Seg_tbPantallasRoles_Insert(Nullable<int> plarol_Id, Nullable<int> rol_Id, Nullable<int> pla_Id, Nullable<int> plarol_UsuarioCrea)
        {
            var plarol_IdParameter = plarol_Id.HasValue ?
                new ObjectParameter("plarol_Id", plarol_Id) :
                new ObjectParameter("plarol_Id", typeof(int));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var pla_IdParameter = pla_Id.HasValue ?
                new ObjectParameter("pla_Id", pla_Id) :
                new ObjectParameter("pla_Id", typeof(int));
    
            var plarol_UsuarioCreaParameter = plarol_UsuarioCrea.HasValue ?
                new ObjectParameter("plarol_UsuarioCrea", plarol_UsuarioCrea) :
                new ObjectParameter("plarol_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Seg_tbPantallasRoles_Insert", plarol_IdParameter, rol_IdParameter, pla_IdParameter, plarol_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Seg_tbPantallasRoles_Update(Nullable<int> plarol_Id, Nullable<int> rol_Id, Nullable<int> pla_Id, Nullable<int> plarol_UsuarioModifica)
        {
            var plarol_IdParameter = plarol_Id.HasValue ?
                new ObjectParameter("plarol_Id", plarol_Id) :
                new ObjectParameter("plarol_Id", typeof(int));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var pla_IdParameter = pla_Id.HasValue ?
                new ObjectParameter("pla_Id", pla_Id) :
                new ObjectParameter("pla_Id", typeof(int));
    
            var plarol_UsuarioModificaParameter = plarol_UsuarioModifica.HasValue ?
                new ObjectParameter("plarol_UsuarioModifica", plarol_UsuarioModifica) :
                new ObjectParameter("plarol_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Seg_tbPantallasRoles_Update", plarol_IdParameter, rol_IdParameter, pla_IdParameter, plarol_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Seg_tbPermisos_Insert(Nullable<int> perm_Id, string perm_Descripcion, Nullable<int> perm_UsuarioCrea)
        {
            var perm_IdParameter = perm_Id.HasValue ?
                new ObjectParameter("perm_Id", perm_Id) :
                new ObjectParameter("perm_Id", typeof(int));
    
            var perm_DescripcionParameter = perm_Descripcion != null ?
                new ObjectParameter("perm_Descripcion", perm_Descripcion) :
                new ObjectParameter("perm_Descripcion", typeof(string));
    
            var perm_UsuarioCreaParameter = perm_UsuarioCrea.HasValue ?
                new ObjectParameter("perm_UsuarioCrea", perm_UsuarioCrea) :
                new ObjectParameter("perm_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Seg_tbPermisos_Insert", perm_IdParameter, perm_DescripcionParameter, perm_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Seg_tbRolesPermisos_Insert(Nullable<int> rol_Id, Nullable<int> perm_Id, Nullable<int> rolpe_UsuarioCrea)
        {
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var perm_IdParameter = perm_Id.HasValue ?
                new ObjectParameter("perm_Id", perm_Id) :
                new ObjectParameter("perm_Id", typeof(int));
    
            var rolpe_UsuarioCreaParameter = rolpe_UsuarioCrea.HasValue ?
                new ObjectParameter("rolpe_UsuarioCrea", rolpe_UsuarioCrea) :
                new ObjectParameter("rolpe_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Seg_tbRolesPermisos_Insert", rol_IdParameter, perm_IdParameter, rolpe_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Seg_tbRolesPermisos_Update(Nullable<int> rolpe_Id, Nullable<int> rol_Id, Nullable<int> perm_Id, Nullable<int> rolpe_UsuarioModifica)
        {
            var rolpe_IdParameter = rolpe_Id.HasValue ?
                new ObjectParameter("rolpe_Id", rolpe_Id) :
                new ObjectParameter("rolpe_Id", typeof(int));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var perm_IdParameter = perm_Id.HasValue ?
                new ObjectParameter("perm_Id", perm_Id) :
                new ObjectParameter("perm_Id", typeof(int));
    
            var rolpe_UsuarioModificaParameter = rolpe_UsuarioModifica.HasValue ?
                new ObjectParameter("rolpe_UsuarioModifica", rolpe_UsuarioModifica) :
                new ObjectParameter("rolpe_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Seg_tbRolesPermisos_Update", rolpe_IdParameter, rol_IdParameter, perm_IdParameter, rolpe_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Seg_tbUsuarios_BloquearUsuario(Nullable<int> usu_Id)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Seg_tbUsuarios_BloquearUsuario", usu_IdParameter);
        }
    
        public virtual ObjectResult<string> UDP_Seg_tbUsuarios_Insert(string usu_NombreUsuario, string usu_Contrasenia)
        {
            var usu_NombreUsuarioParameter = usu_NombreUsuario != null ?
                new ObjectParameter("usu_NombreUsuario", usu_NombreUsuario) :
                new ObjectParameter("usu_NombreUsuario", typeof(string));
    
            var usu_ContraseniaParameter = usu_Contrasenia != null ?
                new ObjectParameter("usu_Contrasenia", usu_Contrasenia) :
                new ObjectParameter("usu_Contrasenia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Seg_tbUsuarios_Insert", usu_NombreUsuarioParameter, usu_ContraseniaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Seg_tbUsuarios_UpdateClave(Nullable<int> usu_Id, string usu_Contrasenia)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var usu_ContraseniaParameter = usu_Contrasenia != null ?
                new ObjectParameter("usu_Contrasenia", usu_Contrasenia) :
                new ObjectParameter("usu_Contrasenia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Seg_tbUsuarios_UpdateClave", usu_IdParameter, usu_ContraseniaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Seg_tbUsuariosRoles_Insert(Nullable<int> usu_Id, Nullable<int> rol_Id, Nullable<int> usurol_UsuarioCrea)
        {
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var usurol_UsuarioCreaParameter = usurol_UsuarioCrea.HasValue ?
                new ObjectParameter("usurol_UsuarioCrea", usurol_UsuarioCrea) :
                new ObjectParameter("usurol_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Seg_tbUsuariosRoles_Insert", usu_IdParameter, rol_IdParameter, usurol_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_SEG_tbUsuariosRoles_Update(Nullable<int> usurol_Id, Nullable<int> usu_Id, Nullable<int> rol_Id, Nullable<int> usurol_UsuarioModifica)
        {
            var usurol_IdParameter = usurol_Id.HasValue ?
                new ObjectParameter("usurol_Id", usurol_Id) :
                new ObjectParameter("usurol_Id", typeof(int));
    
            var usu_IdParameter = usu_Id.HasValue ?
                new ObjectParameter("usu_Id", usu_Id) :
                new ObjectParameter("usu_Id", typeof(int));
    
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var usurol_UsuarioModificaParameter = usurol_UsuarioModifica.HasValue ?
                new ObjectParameter("usurol_UsuarioModifica", usurol_UsuarioModifica) :
                new ObjectParameter("usurol_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_SEG_tbUsuariosRoles_Update", usurol_IdParameter, usu_IdParameter, rol_IdParameter, usurol_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UPD_Seg_tbPantallas_Insert(Nullable<int> pla_Id, string pla_NombreVista, Nullable<int> pla_BloquePadreID, string pla_Identificador, Nullable<int> pla_UsuarioCrea)
        {
            var pla_IdParameter = pla_Id.HasValue ?
                new ObjectParameter("pla_Id", pla_Id) :
                new ObjectParameter("pla_Id", typeof(int));
    
            var pla_NombreVistaParameter = pla_NombreVista != null ?
                new ObjectParameter("pla_NombreVista", pla_NombreVista) :
                new ObjectParameter("pla_NombreVista", typeof(string));
    
            var pla_BloquePadreIDParameter = pla_BloquePadreID.HasValue ?
                new ObjectParameter("pla_BloquePadreID", pla_BloquePadreID) :
                new ObjectParameter("pla_BloquePadreID", typeof(int));
    
            var pla_IdentificadorParameter = pla_Identificador != null ?
                new ObjectParameter("pla_Identificador", pla_Identificador) :
                new ObjectParameter("pla_Identificador", typeof(string));
    
            var pla_UsuarioCreaParameter = pla_UsuarioCrea.HasValue ?
                new ObjectParameter("pla_UsuarioCrea", pla_UsuarioCrea) :
                new ObjectParameter("pla_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UPD_Seg_tbPantallas_Insert", pla_IdParameter, pla_NombreVistaParameter, pla_BloquePadreIDParameter, pla_IdentificadorParameter, pla_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UPD_Seg_tbPantallas_Update(Nullable<int> pla_Id, string pla_NombreVista, Nullable<int> pla_BloquePadreID, string pla_Identificador, Nullable<int> pla_UsuarioModifica)
        {
            var pla_IdParameter = pla_Id.HasValue ?
                new ObjectParameter("pla_Id", pla_Id) :
                new ObjectParameter("pla_Id", typeof(int));
    
            var pla_NombreVistaParameter = pla_NombreVista != null ?
                new ObjectParameter("pla_NombreVista", pla_NombreVista) :
                new ObjectParameter("pla_NombreVista", typeof(string));
    
            var pla_BloquePadreIDParameter = pla_BloquePadreID.HasValue ?
                new ObjectParameter("pla_BloquePadreID", pla_BloquePadreID) :
                new ObjectParameter("pla_BloquePadreID", typeof(int));
    
            var pla_IdentificadorParameter = pla_Identificador != null ?
                new ObjectParameter("pla_Identificador", pla_Identificador) :
                new ObjectParameter("pla_Identificador", typeof(string));
    
            var pla_UsuarioModificaParameter = pla_UsuarioModifica.HasValue ?
                new ObjectParameter("pla_UsuarioModifica", pla_UsuarioModifica) :
                new ObjectParameter("pla_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UPD_Seg_tbPantallas_Update", pla_IdParameter, pla_NombreVistaParameter, pla_BloquePadreIDParameter, pla_IdentificadorParameter, pla_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UPD_Seg_tbPermisos_Update(Nullable<int> perm_Id, string perm_Descripcion, Nullable<int> perm_UsuarioModifica)
        {
            var perm_IdParameter = perm_Id.HasValue ?
                new ObjectParameter("perm_Id", perm_Id) :
                new ObjectParameter("perm_Id", typeof(int));
    
            var perm_DescripcionParameter = perm_Descripcion != null ?
                new ObjectParameter("perm_Descripcion", perm_Descripcion) :
                new ObjectParameter("perm_Descripcion", typeof(string));
    
            var perm_UsuarioModificaParameter = perm_UsuarioModifica.HasValue ?
                new ObjectParameter("perm_UsuarioModifica", perm_UsuarioModifica) :
                new ObjectParameter("perm_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UPD_Seg_tbPermisos_Update", perm_IdParameter, perm_DescripcionParameter, perm_UsuarioModificaParameter);
        }
    
        public virtual ObjectResult<string> UPD_Seg_tbRoles_Insert(string rol_Descripcion, Nullable<int> rol_UsuarioCrea)
        {
            var rol_DescripcionParameter = rol_Descripcion != null ?
                new ObjectParameter("rol_Descripcion", rol_Descripcion) :
                new ObjectParameter("rol_Descripcion", typeof(string));
    
            var rol_UsuarioCreaParameter = rol_UsuarioCrea.HasValue ?
                new ObjectParameter("rol_UsuarioCrea", rol_UsuarioCrea) :
                new ObjectParameter("rol_UsuarioCrea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UPD_Seg_tbRoles_Insert", rol_DescripcionParameter, rol_UsuarioCreaParameter);
        }
    
        public virtual ObjectResult<string> UPD_Seg_tbRoles_Update(Nullable<int> rol_Id, string rol_Descripcion, Nullable<int> rol_UsuarioModifica)
        {
            var rol_IdParameter = rol_Id.HasValue ?
                new ObjectParameter("rol_Id", rol_Id) :
                new ObjectParameter("rol_Id", typeof(int));
    
            var rol_DescripcionParameter = rol_Descripcion != null ?
                new ObjectParameter("rol_Descripcion", rol_Descripcion) :
                new ObjectParameter("rol_Descripcion", typeof(string));
    
            var rol_UsuarioModificaParameter = rol_UsuarioModifica.HasValue ?
                new ObjectParameter("rol_UsuarioModifica", rol_UsuarioModifica) :
                new ObjectParameter("rol_UsuarioModifica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UPD_Seg_tbRoles_Update", rol_IdParameter, rol_DescripcionParameter, rol_UsuarioModificaParameter);
        }
    }
}
