//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCategoriaProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCategoriaProductos()
        {
            this.tbSubCategoriaProductos = new HashSet<tbSubCategoriaProductos>();
        }
    
        public int cprod_Id { get; set; }
        public string cprod_Descripcion { get; set; }
        public int cprod_UsuarioCrea { get; set; }
        public System.DateTime cprod_FechaCrea { get; set; }
        public Nullable<int> cprod_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> cprod_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSubCategoriaProductos> tbSubCategoriaProductos { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
