//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCiudades
    {
        public int ciud_Id { get; set; }
        public string ciud_Descripcion { get; set; }
        public int ciud_CodigoPostal { get; set; }
        public int depto_Id { get; set; }
        public bool ciud_Estado { get; set; }
        public int ciud_UsuarioCrea { get; set; }
        public System.DateTime ciud_FechaCrea { get; set; }
        public Nullable<int> ciud_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> ciud_FechaModifica { get; set; }
    
        public virtual tbDepartamentos tbDepartamentos { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
