//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClientes
    {
        public int clte_Id { get; set; }
        public int rang_Id { get; set; }
        public bool clte_EsActivo { get; set; }
        public int per_Id { get; set; }
        public bool clte_Estado { get; set; }
        public int clte_UsuarioCrea { get; set; }
        public System.DateTime clte_FechaCrea { get; set; }
        public Nullable<int> clte_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> clte_FechaModifica { get; set; }
    
        public virtual tbPersonas tbPersonas { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
