//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDepartamentos
    {
        public int depto_Id { get; set; }
        public string depto_Descripcion { get; set; }
        public int depto_CodigoDepartamento { get; set; }
        public int pais_Id { get; set; }
        public bool depto_EsActivo { get; set; }
        public int depto_UsuarioCrea { get; set; }
        public System.DateTime depto_FechaCrea { get; set; }
        public Nullable<int> depto_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> depto_FechaModifica { get; set; }
    
        public virtual tbCiudades tbCiudades { get; set; }
        public virtual tbPais tbPais { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
