//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDirecciones
    {
        public int dir_Id { get; set; }
        public string dir_Descripcion1 { get; set; }
        public string dir_Descripcion2 { get; set; }
        public int ciud_Id { get; set; }
        public bool dir_Estado { get; set; }
        public string dir_TipoEntidad { get; set; }
        public Nullable<System.DateTime> dir_FechaFinUsoDireccion { get; set; }
        public int dir_UsuarioCrea { get; set; }
        public System.DateTime dir_FechaCrea { get; set; }
        public Nullable<int> dir_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> dir_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
