//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbImagenProductos
    {
        public int impro_Id { get; set; }
        public Nullable<int> prod_Id { get; set; }
        public string impro_Imagen { get; set; }
    
        public virtual tbProductos tbProductos { get; set; }
    }
}
