//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMarcasComerciales
    {
        public int mc_Id { get; set; }
        public string mc_Descripcion { get; set; }
        public string mc_Foto { get; set; }
        public int mc_UsuarioCrea { get; set; }
        public System.DateTime mc_FechaCrea { get; set; }
        public Nullable<int> mc_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> mc_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
