//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPantallas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPantallas()
        {
            this.tbPantallasRoles = new HashSet<tbPantallasRoles>();
        }
    
        public int pla_Id { get; set; }
        public string pla_NombreVista { get; set; }
        public Nullable<int> pla_BloquePadreID { get; set; }
        public string pla_Identificador { get; set; }
        public int pla_UsuarioCrea { get; set; }
        public System.DateTime pla_FechaCrea { get; set; }
        public Nullable<int> pla_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> pla_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPantallasRoles> tbPantallasRoles { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
