//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPantallasRoles
    {
        public int plarol_Id { get; set; }
        public int rol_Id { get; set; }
        public int pla_Id { get; set; }
        public int plarol_UsuarioCrea { get; set; }
        public System.DateTime plarol_FechaCrea { get; set; }
        public Nullable<int> plarol_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> plarol_FechaModifica { get; set; }
    
        public virtual tbPantallas tbPantallas { get; set; }
        public virtual tbRoles tbRoles { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
