//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRangos
    {
        public int rang_Id { get; set; }
        public string rang_Descripcion { get; set; }
        public bool rang_Estado { get; set; }
        public int rang_UsuarioCrea { get; set; }
        public System.DateTime rang_FechaCrea { get; set; }
        public Nullable<int> rang_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> rang_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
