//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRolesPermisos
    {
        public int rolpe_Id { get; set; }
        public int rol_Id { get; set; }
        public int perm_Id { get; set; }
        public int rolpe_UsuarioCrea { get; set; }
        public System.DateTime rolpe_FechaCrea { get; set; }
        public Nullable<int> rolpe_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> rolpe_FechaModifica { get; set; }
    
        public virtual tbPermisos tbPermisos { get; set; }
        public virtual tbRoles tbRoles { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
