//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_SpartansCustom_Rifas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSubCategoriaProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSubCategoriaProductos()
        {
            this.tbProductos = new HashSet<tbProductos>();
        }
    
        public int scprod_Id { get; set; }
        public Nullable<int> cprod_Id { get; set; }
        public string scprod_Descripcion { get; set; }
        public int scprod_UsuarioCrea { get; set; }
        public System.DateTime scprod_FechaCrea { get; set; }
        public Nullable<int> scprod_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> scprod_FechaModifica { get; set; }
    
        public virtual tbCategoriaProductos tbCategoriaProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProductos> tbProductos { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
